name: WAF on RE deploy

on:
  push:
    branches:
      - deploy-waf-re
  pull_request:

jobs:
  deploy:
  # This job deals with deployment Arcadia in Azure cloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azure/vm
    steps:
      - uses: actions/checkout@v3        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
      - name: Deploy infra
        env:
          TF_VAR_azure_subscription_id: ${{ secrets.TF_VAR_AZURE_SUBSCRIPTION_ID }}
          TF_VAR_azure_subscription_tenant_id: ${{ secrets.TF_VAR_AZURE_SUBSCRIPTION_TENANT_ID }}
          TF_VAR_azure_service_principal_appid: ${{ secrets.TF_VAR_AZURE_SERVICE_PRINCIPAL_APPID }}
          TF_VAR_azure_service_principal_password: ${{ secrets.TF_VAR_AZURE_SERVICE_PRINCIPAL_PASSWORD }}
        run: | 
          cd terraform
          terraform init
          terraform plan 
          terraform apply --auto-approve     
      - name: Upload tfstate file
        uses: actions/upload-artifact@v3
        with:
          name: tfstate
          path: terraform/terraform.tfstate
